export const DARK_MODE = {
  ON: 'DARK_MODE_ON',
  OFF: 'DARK_MODE_OFF',
};

export const STORY = {
  SET_FILTER: 'STORY_SET_FILTER',
  FETCH_ALL: 'STORY_FETCH_ALL',
  FETCH_ALL_SUCCESS: 'STORY_FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'STORY_FETCH_ALL_FAILURE',
};

export const PAGE = {
  NEXT: 'PAGE_NEXT',
  PREV: 'PAGE_PREV',
};
